#!/bin/sh
# Command delay time
sleeptime=0.0001
doubletime=1

# Confirm Embark
confirmX=1450
confirmY=800

# Formation 1st Multi battle guest
formationX=1200
formationY=800

# Reload multi quests
RX=2200
RY=225

# Battle Settings
battleSettingsX=600
battleSettingsY=775

# Accept Friend / Apply
applyX=1500
applyY=1000

# Close quest details
closeDetailsX=2000
closeDetailsY=100

# Quest Details
questDetailsX=2100
questDetailsY=125

ZX=2350
ZY=150

# Embark
embarkX=2000
embarkY=1000