#!/bin/sh
# Command delay time
sleeptime=0.3
doubletime=1.5

# Confirm Embark
confirmX=825
confirmY=500

# Formation 1st Multi battle guest
formationX=700
formationY=525

# Reload multi quests
RX=2200
RY=225

# Battle Settings
battleSettingsX=275
battleSettingsY=500

# Accept Friend / Apply
applyX=825
applyY=625

# Close quest details
closeDetailsX=1200
closeDetailsY=50

# Quest Details
questDetailsX=1300
questDetailsY=75

ZX=2350
ZY=150

# Embark
embarkX=1225
embarkY=675
